image: docker.ucalgary.ca/rms-utils/rms-ci:latest

stages:
  - build
  - mirror

variables:
  BUILD_CONTEXT_PATH: '.'
  COMPOSE_PROJECT_NAME: $DOCKER_PROJECT_NAME-$CI_BUILD_REF_NAME
  IMAGE_TAG: $CI_BUILD_REF_NAME
  SWARM_RAFT_CONSENSUS_DELAY: '30'

Build Image: &build_image
  stage: build
  script:
    - if [ -z ${CI_REGISTRY_IMAGE+x} ]; then
        export CI_REGISTRY_IMAGE=`basename $CI_BUILD_REPO`; fi
    - if [ -n "${CI_BUILD_TOKEN}" ]; then
        docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY; fi
    - docker build
        --pull
        --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG
        $BUILD_CONTEXT_PATH
    - if [ -n "${CI_BUILD_TOKEN}" ]; then
        docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG; fi

Push Image to AWS:
  stage: mirror
  script:
    - aws ecr get-login --region $AWS_REGION | sh
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker tag $CI_REGISTRY_IMAGE:$IMAGE_TAG $AWS_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
    - docker push $AWS_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
    - docker rmi $AWS_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
  only:
    - master
    - tags

Push Repo to AWS:
  stage: mirror
  script:
    - git push --mirror https://$AWS_CC_GIT_USERNAME:$AWS_CC_GIT_PASSWORD@git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/$CI_PROJECT_NAME
  only:
    - master
    - tags
